const mockOpenApi = {
    "components":{
        "securitySchemes":{
            "PartnerTokenAuth":{
                "description":"User authorisation for partners.",
                "in":"header",
                "name":"KW-Partner-Token",
                "type":"apiKey",
                "x-apikeyInfoFunc":"kw.openapi.authentication.get_inactive_token_from_apikey"
            },
            "SimpleTokenAuth":{
                "description":"User authorisation based on simple token.",
                "in":"header",
                "name":"KW-Simple-Token",
                "type":"apiKey",
                "x-apikeyInfoFunc":"kw.openapi.authentication.get_inactive_token_from_apikey"
            },
            "TokenAuth":{
                "description":"User authorisation based on JSON Web Token.",
                "in":"header",
                "name":"KW-Auth-Token",
                "type":"apiKey",
                "x-apikeyInfoFunc":"kw.openapi.authentication.get_inactive_token_from_apikey"
            },
            "UserAppTokenAuth":{
                "description":"User authorisation based on UserApp token.",
                "in":"header",
                "name":"KW-User-Token",
                "type":"apiKey",
                "x-apikeyInfoFunc":"kw.openapi.authentication.get_inactive_token_from_apikey"
            }
        }
    },
    "info":{
        "contact":{
            "name":"Booking Team",
            "x-slack":"#plz-booking-backend"
        },
        "description":"Backend for Frontend API (mid-layer between FE and MMB API).",
        "title":"Kiwi.com BFF API",
        "version":"0.1.0",
        "x-visibility":"unlisted"
    },
    "openapi":"3.0.2",
    "paths":{
        "/bookings/{booking_id}/invoices":{
            "get":{
                "operationId":"kw.mambo.bff.invoices.handlers.get_invoices_view",
                "parameters":[
                    {
                        "description":"Optional language code for localisation of the output, iso-639-1 standard.",
                        "in":"query",
                        "name":"language",
                        "required":false,
                        "schema":{
                            "maxLength":2,
                            "minLength":2,
                            "type":"string"
                        }
                    }
                ],
                "responses":{
                    "200":{
                        "content":{
                            "application/json":{
                                "schema":{
                                    "additionalProperties":false,
                                    "properties":{
                                        "common":{
                                            "additionalProperties":false,
                                            "description":"Booking info common for all kinds of views.",
                                            "properties":{
                                                "basket":{
                                                    "additionalProperties":false,
                                                    "nullable":true,
                                                    "properties":{
                                                        "booking_items":{
                                                            "description":"Booking level e.g. service package, itinerary change",
                                                            "items":{
                                                                "additionalProperties":false,
                                                                "properties":{
                                                                    "category":{
                                                                        "enum":[
                                                                            "assisted_refund",
                                                                            "axa_insurance",
                                                                            "bags",
                                                                            "booking_restore",
                                                                            "extras.other",
                                                                            "extras.passenger_details_change",
                                                                            "extras.change_flight",
                                                                            "extras.bags",
                                                                            "flights",
                                                                            "flight_event",
                                                                            "handling_fee",
                                                                            "itinerary_change",
                                                                            "meals",
                                                                            "passenger_details_change",
                                                                            "price_change",
                                                                            "priority_boarding",
                                                                            "seating",
                                                                            "service_package",
                                                                            "service.flight_change",
                                                                            "service.infant",
                                                                            "service.priority_boarding",
                                                                            "service.upgrade_baggage",
                                                                            "service.meals_on_board",
                                                                            "service.special_assistance",
                                                                            "service.travelling_with_pets",
                                                                            "service.other",
                                                                            "service.sports_equipment",
                                                                            "service.baggage",
                                                                            "service.musical_equipment",
                                                                            "service.allocated_seating"
                                                                        ],
                                                                        "type":"string"
                                                                    },
                                                                    "price":{
                                                                        "additionalProperties":false,
                                                                        "description":"Price object with amount expressed in currency and all price components added into the amount.\n",
                                                                        "properties":{
                                                                            "amount":{
                                                                                "description":"Amount of money expressed in currency.",
                                                                                "example":"20.00",
                                                                                "format":"decimal",
                                                                                "type":"string"
                                                                            },
                                                                            "base":{
                                                                                "description":"The base price of a product, usually from the transport provider.",
                                                                                "example":"10.00",
                                                                                "format":"decimal",
                                                                                "type":"string"
                                                                            },
                                                                            "currency":{
                                                                                "description":"Price currency, 3 letter currency code as defined by ISO-4217.",
                                                                                "example":"EUR",
                                                                                "format":"iso-4217",
                                                                                "type":"string"
                                                                            },
                                                                            "merchant":{
                                                                                "description":"Additional third-party fees like tax etc. Displayed for legal reasons.\n",
                                                                                "example":"5.00",
                                                                                "format":"decimal",
                                                                                "type":"string"
                                                                            },
                                                                            "service":{
                                                                                "description":"Service fee, known as margin, dynamically calculated from the base price depending on business rules.\n",
                                                                                "example":"2.00",
                                                                                "format":"decimal",
                                                                                "type":"string"
                                                                            },
                                                                            "service_flat":{
                                                                                "description":"Service flat fee with always the same price added to the base price amount depending on business rules.\n",
                                                                                "example":"3.00",
                                                                                "format":"decimal",
                                                                                "type":"string"
                                                                            }
                                                                        },
                                                                        "required":[
                                                                            "amount",
                                                                            "currency",
                                                                            "base",
                                                                            "service",
                                                                            "service_flat",
                                                                            "merchant"
                                                                        ],
                                                                        "title":"Price",
                                                                        "type":"object"
                                                                    },
                                                                    "quantity":{
                                                                        "type":"number"
                                                                    },
                                                                    "segment":{
                                                                        "properties":{
                                                                            "arrival_code":{
                                                                                "type":"string"
                                                                            },
                                                                            "departure_code":{
                                                                                "type":"string"
                                                                            }
                                                                        },
                                                                        "type":"object"
                                                                    }
                                                                },
                                                                "required":[
                                                                    "category",
                                                                    "price",
                                                                    "quantity"
                                                                ],
                                                                "type":"object"
                                                            },
                                                            "type":"array"
                                                        },
                                                        "id":{
                                                            "description":"ID of the shopping basket.",
                                                            "example":"1ba89ded-6d4f-48d1-a75f-943706105939",
                                                            "format":"uuid",
                                                            "type":"string"
                                                        },
                                                        "is_valid":{
                                                            "description":"Flag if shopping basket is valid and ready for payment, if not, items contain unreliable info.",
                                                            "type":"boolean"
                                                        },
                                                        "item_count":{
                                                            "description":"Number of items in the basket",
                                                            "type":"integer"
                                                        },
                                                        "legacy_items":{
                                                            "description":"Legacy items with uncertain binding to pap or segment (Portalo other and Nest ancillaries)",
                                                            "items":{
                                                                "additionalProperties":false,
                                                                "properties":{
                                                                    "category":{
                                                                        "enum":[
                                                                            "assisted_refund",
                                                                            "axa_insurance",
                                                                            "bags",
                                                                            "booking_restore",
                                                                            "extras.other",
                                                                            "extras.passenger_details_change",
                                                                            "extras.change_flight",
                                                                            "extras.bags",
                                                                            "flights",
                                                                            "flight_event",
                                                                            "handling_fee",
                                                                            "itinerary_change",
                                                                            "meals",
                                                                            "passenger_details_change",
                                                                            "price_change",
                                                                            "priority_boarding",
                                                                            "seating",
                                                                            "service_package",
                                                                            "service.flight_change",
                                                                            "service.infant",
                                                                            "service.priority_boarding",
                                                                            "service.upgrade_baggage",
                                                                            "service.meals_on_board",
                                                                            "service.special_assistance",
                                                                            "service.travelling_with_pets",
                                                                            "service.other",
                                                                            "service.sports_equipment",
                                                                            "service.baggage",
                                                                            "service.musical_equipment",
                                                                            "service.allocated_seating"
                                                                        ],
                                                                        "type":"string"
                                                                    },
                                                                    "price":{
                                                                        "additionalProperties":false,
                                                                        "description":"Price object with amount expressed in currency and all price components added into the amount.\n",
                                                                        "properties":{
                                                                            "amount":{
                                                                                "description":"Amount of money expressed in currency.",
                                                                                "example":"20.00",
                                                                                "format":"decimal",
                                                                                "type":"string"
                                                                            },
                                                                            "base":{
                                                                                "description":"The base price of a product, usually from the transport provider.",
                                                                                "example":"10.00",
                                                                                "format":"decimal",
                                                                                "type":"string"
                                                                            },
                                                                            "currency":{
                                                                                "description":"Price currency, 3 letter currency code as defined by ISO-4217.",
                                                                                "example":"EUR",
                                                                                "format":"iso-4217",
                                                                                "type":"string"
                                                                            },
                                                                            "merchant":{
                                                                                "description":"Additional third-party fees like tax etc. Displayed for legal reasons.\n",
                                                                                "example":"5.00",
                                                                                "format":"decimal",
                                                                                "type":"string"
                                                                            },
                                                                            "service":{
                                                                                "description":"Service fee, known as margin, dynamically calculated from the base price depending on business rules.\n",
                                                                                "example":"2.00",
                                                                                "format":"decimal",
                                                                                "type":"string"
                                                                            },
                                                                            "service_flat":{
                                                                                "description":"Service flat fee with always the same price added to the base price amount depending on business rules.\n",
                                                                                "example":"3.00",
                                                                                "format":"decimal",
                                                                                "type":"string"
                                                                            }
                                                                        },
                                                                        "required":[
                                                                            "amount",
                                                                            "currency",
                                                                            "base",
                                                                            "service",
                                                                            "service_flat",
                                                                            "merchant"
                                                                        ],
                                                                        "title":"Price",
                                                                        "type":"object"
                                                                    },
                                                                    "quantity":{
                                                                        "type":"number"
                                                                    },
                                                                    "segment":{
                                                                        "properties":{
                                                                            "arrival_code":{
                                                                                "type":"string"
                                                                            },
                                                                            "departure_code":{
                                                                                "type":"string"
                                                                            }
                                                                        },
                                                                        "type":"object"
                                                                    }
                                                                },
                                                                "required":[
                                                                    "category",
                                                                    "price",
                                                                    "quantity"
                                                                ],
                                                                "type":"object"
                                                            },
                                                            "type":"array"
                                                        },
                                                        "passengers_items":{
                                                            "description":"Items split per passenger",
                                                            "items":{
                                                                "additionalProperties":false,
                                                                "properties":{
                                                                    "basket_items":{
                                                                        "description":"Passenger level items e.g. service package, itinerary change",
                                                                        "items":{
                                                                            "additionalProperties":false,
                                                                            "properties":{
                                                                                "category":{
                                                                                    "enum":[
                                                                                        "assisted_refund",
                                                                                        "axa_insurance",
                                                                                        "bags",
                                                                                        "booking_restore",
                                                                                        "extras.other",
                                                                                        "extras.passenger_details_change",
                                                                                        "extras.change_flight",
                                                                                        "extras.bags",
                                                                                        "flights",
                                                                                        "flight_event",
                                                                                        "handling_fee",
                                                                                        "itinerary_change",
                                                                                        "meals",
                                                                                        "passenger_details_change",
                                                                                        "price_change",
                                                                                        "priority_boarding",
                                                                                        "seating",
                                                                                        "service_package",
                                                                                        "service.flight_change",
                                                                                        "service.infant",
                                                                                        "service.priority_boarding",
                                                                                        "service.upgrade_baggage",
                                                                                        "service.meals_on_board",
                                                                                        "service.special_assistance",
                                                                                        "service.travelling_with_pets",
                                                                                        "service.other",
                                                                                        "service.sports_equipment",
                                                                                        "service.baggage",
                                                                                        "service.musical_equipment",
                                                                                        "service.allocated_seating"
                                                                                    ],
                                                                                    "type":"string"
                                                                                },
                                                                                "price":{
                                                                                    "additionalProperties":false,
                                                                                    "description":"Price object with amount expressed in currency and all price components added into the amount.\n",
                                                                                    "properties":{
                                                                                        "amount":{
                                                                                            "description":"Amount of money expressed in currency.",
                                                                                            "example":"20.00",
                                                                                            "format":"decimal",
                                                                                            "type":"string"
                                                                                        },
                                                                                        "base":{
                                                                                            "description":"The base price of a product, usually from the transport provider.",
                                                                                            "example":"10.00",
                                                                                            "format":"decimal",
                                                                                            "type":"string"
                                                                                        },
                                                                                        "currency":{
                                                                                            "description":"Price currency, 3 letter currency code as defined by ISO-4217.",
                                                                                            "example":"EUR",
                                                                                            "format":"iso-4217",
                                                                                            "type":"string"
                                                                                        },
                                                                                        "merchant":{
                                                                                            "description":"Additional third-party fees like tax etc. Displayed for legal reasons.\n",
                                                                                            "example":"5.00",
                                                                                            "format":"decimal",
                                                                                            "type":"string"
                                                                                        },
                                                                                        "service":{
                                                                                            "description":"Service fee, known as margin, dynamically calculated from the base price depending on business rules.\n",
                                                                                            "example":"2.00",
                                                                                            "format":"decimal",
                                                                                            "type":"string"
                                                                                        },
                                                                                        "service_flat":{
                                                                                            "description":"Service flat fee with always the same price added to the base price amount depending on business rules.\n",
                                                                                            "example":"3.00",
                                                                                            "format":"decimal",
                                                                                            "type":"string"
                                                                                        }
                                                                                    },
                                                                                    "required":[
                                                                                        "amount",
                                                                                        "currency",
                                                                                        "base",
                                                                                        "service",
                                                                                        "service_flat",
                                                                                        "merchant"
                                                                                    ],
                                                                                    "title":"Price",
                                                                                    "type":"object"
                                                                                },
                                                                                "quantity":{
                                                                                    "type":"number"
                                                                                },
                                                                                "segment":{
                                                                                    "properties":{
                                                                                        "arrival_code":{
                                                                                            "type":"string"
                                                                                        },
                                                                                        "departure_code":{
                                                                                            "type":"string"
                                                                                        }
                                                                                    },
                                                                                    "type":"object"
                                                                                }
                                                                            },
                                                                            "required":[
                                                                                "category",
                                                                                "price",
                                                                                "quantity"
                                                                            ],
                                                                            "type":"object"
                                                                        },
                                                                        "type":"array"
                                                                    },
                                                                    "passenger":{
                                                                        "properties":{
                                                                            "date_of_birth":{
                                                                                "format":"date",
                                                                                "type":"string"
                                                                            },
                                                                            "name":{
                                                                                "type":"string"
                                                                            }
                                                                        },
                                                                        "required":[
                                                                            "name",
                                                                            "date_of_birth"
                                                                        ],
                                                                        "type":"object"
                                                                    }
                                                                },
                                                                "required":[
                                                                    "basket_items",
                                                                    "passenger"
                                                                ],
                                                                "type":"object"
                                                            },
                                                            "type":"array"
                                                        },
                                                        "price_breakdown":{
                                                            "additionalProperties":false,
                                                            "properties":{
                                                                "base_price":{
                                                                    "additionalProperties":false,
                                                                    "description":"Amount of money expressed in currency.",
                                                                    "properties":{
                                                                        "amount":{
                                                                            "description":"Amount of money.",
                                                                            "example":"20.00",
                                                                            "format":"decimal",
                                                                            "type":"string"
                                                                        },
                                                                        "currency":{
                                                                            "description":"Price currency, 3 letter currency code as defined by ISO-4217.",
                                                                            "example":"EUR",
                                                                            "format":"iso-4217",
                                                                            "type":"string"
                                                                        }
                                                                    },
                                                                    "required":[
                                                                        "amount",
                                                                        "currency"
                                                                    ],
                                                                    "title":"Simple price",
                                                                    "type":"object"
                                                                },
                                                                "processing_fee":{
                                                                    "additionalProperties":false,
                                                                    "description":"Amount of money expressed in currency.",
                                                                    "properties":{
                                                                        "amount":{
                                                                            "description":"Amount of money.",
                                                                            "example":"20.00",
                                                                            "format":"decimal",
                                                                            "type":"string"
                                                                        },
                                                                        "currency":{
                                                                            "description":"Price currency, 3 letter currency code as defined by ISO-4217.",
                                                                            "example":"EUR",
                                                                            "format":"iso-4217",
                                                                            "type":"string"
                                                                        }
                                                                    },
                                                                    "required":[
                                                                        "amount",
                                                                        "currency"
                                                                    ],
                                                                    "title":"Simple price",
                                                                    "type":"object"
                                                                },
                                                                "service_fee":{
                                                                    "additionalProperties":false,
                                                                    "description":"Amount of money expressed in currency.",
                                                                    "properties":{
                                                                        "amount":{
                                                                            "description":"Amount of money.",
                                                                            "example":"20.00",
                                                                            "format":"decimal",
                                                                            "type":"string"
                                                                        },
                                                                        "currency":{
                                                                            "description":"Price currency, 3 letter currency code as defined by ISO-4217.",
                                                                            "example":"EUR",
                                                                            "format":"iso-4217",
                                                                            "type":"string"
                                                                        }
                                                                    },
                                                                    "required":[
                                                                        "amount",
                                                                        "currency"
                                                                    ],
                                                                    "title":"Simple price",
                                                                    "type":"object"
                                                                },
                                                                "total_price":{
                                                                    "additionalProperties":false,
                                                                    "description":"Amount of money expressed in currency.",
                                                                    "properties":{
                                                                        "amount":{
                                                                            "description":"Amount of money.",
                                                                            "example":"20.00",
                                                                            "format":"decimal",
                                                                            "type":"string"
                                                                        },
                                                                        "currency":{
                                                                            "description":"Price currency, 3 letter currency code as defined by ISO-4217.",
                                                                            "example":"EUR",
                                                                            "format":"iso-4217",
                                                                            "type":"string"
                                                                        }
                                                                    },
                                                                    "required":[
                                                                        "amount",
                                                                        "currency"
                                                                    ],
                                                                    "title":"Simple price",
                                                                    "type":"object"
                                                                }
                                                            },
                                                            "required":[
                                                                "base_price",
                                                                "processing_fee",
                                                                "service_fee",
                                                                "total_price"
                                                            ],
                                                            "type":"object"
                                                        },
                                                        "service_package":{
                                                            "nullable":true,
                                                            "properties":{
                                                                "fee":{
                                                                    "additionalProperties":false,
                                                                    "description":"Amount of money expressed in currency.",
                                                                    "properties":{
                                                                        "amount":{
                                                                            "description":"Amount of money.",
                                                                            "example":"20.00",
                                                                            "format":"decimal",
                                                                            "type":"string"
                                                                        },
                                                                        "currency":{
                                                                            "description":"Price currency, 3 letter currency code as defined by ISO-4217.",
                                                                            "example":"EUR",
                                                                            "format":"iso-4217",
                                                                            "type":"string"
                                                                        }
                                                                    },
                                                                    "required":[
                                                                        "amount",
                                                                        "currency"
                                                                    ],
                                                                    "title":"Simple price",
                                                                    "type":"object"
                                                                },
                                                                "level":{
                                                                    "description":"Level of service package.",
                                                                    "enum":[
                                                                        "basic",
                                                                        "plus",
                                                                        "premium"
                                                                    ],
                                                                    "type":"string"
                                                                }
                                                            },
                                                            "required":[
                                                                "fee",
                                                                "level"
                                                            ],
                                                            "type":"object"
                                                        },
                                                        "status":{
                                                            "enum":[
                                                                "open",
                                                                "payment_processing",
                                                                "paid",
                                                                "expired"
                                                            ],
                                                            "title":"Shopping basket status",
                                                            "type":"string"
                                                        },
                                                        "validation_errors":{
                                                            "description":"All validation errors.",
                                                            "items":{
                                                                "additionalProperties":false,
                                                                "properties":{
                                                                    "item_category":{
                                                                        "enum":[
                                                                            "assisted_refund",
                                                                            "axa_insurance",
                                                                            "bags",
                                                                            "booking_restore",
                                                                            "extras.other",
                                                                            "extras.passenger_details_change",
                                                                            "flight_event",
                                                                            "handling_fee",
                                                                            "itinerary_change",
                                                                            "meals",
                                                                            "passenger_details_change",
                                                                            "price_change",
                                                                            "priority_boarding",
                                                                            "seating",
                                                                            "service.allocated_seating",
                                                                            "service.baggage",
                                                                            "service.infant",
                                                                            "service.meals_on_board",
                                                                            "service.musical_equipment",
                                                                            "service.other",
                                                                            "service.priority_boarding",
                                                                            "service.special_assistance",
                                                                            "service.sports_equipment",
                                                                            "service.travelling_with_pets",
                                                                            "service.upgrade_baggage",
                                                                            "service_package"
                                                                        ],
                                                                        "nullable":true,
                                                                        "type":"string"
                                                                    },
                                                                    "item_index":{
                                                                        "example":0,
                                                                        "nullable":true,
                                                                        "type":"integer"
                                                                    },
                                                                    "message":{
                                                                        "example":"provided handling_fee is substantially different from the expected handling_fee",
                                                                        "type":"string"
                                                                    }
                                                                },
                                                                "required":[
                                                                    "item_category",
                                                                    "item_index",
                                                                    "message"
                                                                ],
                                                                "title":"Shopping basket validation error",
                                                                "type":"object"
                                                            },
                                                            "type":"array"
                                                        }
                                                    },
                                                    "required":[
                                                        "id",
                                                        "status"
                                                    ],
                                                    "type":"object"
                                                },
                                                "header":{
                                                    "additionalProperties":false,
                                                    "properties":{
                                                        "display_stops":{
                                                            "description":"Itinerary stops, ordered chronologicaly.",
                                                            "items":{
                                                                "properties":{
                                                                    "name":{
                                                                        "description":"City name, possibly localized.",
                                                                        "type":"string"
                                                                    }
                                                                },
                                                                "required":[
                                                                    "name"
                                                                ],
                                                                "type":"object"
                                                            },
                                                            "minItems":1,
                                                            "type":"array"
                                                        },
                                                        "itinerary_type":{
                                                            "enum":[
                                                                "one_way",
                                                                "return",
                                                                "multicity",
                                                                "nomad"
                                                            ],
                                                            "nullable":true,
                                                            "type":"string"
                                                        }
                                                    },
                                                    "required":[
                                                        "itinerary_type",
                                                        "display_stops"
                                                    ],
                                                    "type":"object"
                                                },
                                                "restrictions":{
                                                    "description":"List of restrictions denying proceeding to requested page",
                                                    "items":{
                                                        "properties":{
                                                            "reason":{
                                                                "description":"Reason of restriction",
                                                                "enum":[
                                                                    "pending_refunds",
                                                                    "schedule_change",
                                                                    "booking_status_processing",
                                                                    "booking_status_refunding",
                                                                    "booking_status_refunded",
                                                                    "booking_status_change_in_progress"
                                                                ],
                                                                "type":"string"
                                                            },
                                                            "restriction_level":{
                                                                "enum":[
                                                                    "full",
                                                                    "partial"
                                                                ],
                                                                "type":"string"
                                                            }
                                                        },
                                                        "required":[
                                                            "reason",
                                                            "level"
                                                        ],
                                                        "type":"object"
                                                    },
                                                    "type":"array"
                                                }
                                            },
                                            "required":[
                                                "header"
                                            ],
                                            "title":"Common booking info view",
                                            "type":"object"
                                        },
                                        "invoices":{
                                            "items":{
                                                "additionalProperties":false,
                                                "description":"An invoice view.",
                                                "properties":{
                                                    "category":{
                                                        "enum":[
                                                            "extras",
                                                            "extras.other",
                                                            "seating",
                                                            "meals",
                                                            "extras.change_flight",
                                                            "update_insurances",
                                                            "axa_us_insurance",
                                                            "cover_more_insurance",
                                                            "extras.bags",
                                                            "bags",
                                                            "price_change",
                                                            "flights",
                                                            "extras.passenger_details_change",
                                                            "passenger_details_change",
                                                            "booking.restore",
                                                            "assisted_refund",
                                                            "service.allocated_seating",
                                                            "service.meals_on_board",
                                                            "service.sports_equipment",
                                                            "service.musical_equipment",
                                                            "service.travelling_with_pets",
                                                            "service.special_assistance",
                                                            "service.baggage",
                                                            "service.flight_change",
                                                            "service.infant",
                                                            "service.priority_boarding",
                                                            "service.other",
                                                            "service.upgrade_baggage",
                                                            "service_package",
                                                            "booking"
                                                        ],
                                                        "title":"Extra categories enum",
                                                        "type":"string"
                                                    },
                                                    "created_at":{
                                                        "example":"2018-01-11T13:15:34.764914",
                                                        "format":"date-time",
                                                        "readOnly":true,
                                                        "type":"string"
                                                    },
                                                    "files":{
                                                        "items":{
                                                            "additionalProperties":false,
                                                            "description":"An invoice, containing the information about country of invoice and the identifiers of related items.",
                                                            "properties":{
                                                                "type":{
                                                                    "description":"Type of invoice document. Russian invoices uphold different standards.",
                                                                    "enum":[
                                                                        "invoice",
                                                                        "russian_invoice"
                                                                    ],
                                                                    "example":"invoice",
                                                                    "type":"string"
                                                                },
                                                                "url":{
                                                                    "example":"https://example.kiwi.com/invoice/123",
                                                                    "type":"string"
                                                                }
                                                            },
                                                            "required":[
                                                                "type",
                                                                "url"
                                                            ],
                                                            "title":"Invoice file view",
                                                            "type":"object"
                                                        },
                                                        "type":"array"
                                                    }
                                                },
                                                "required":[
                                                    "category",
                                                    "created_at",
                                                    "files"
                                                ],
                                                "title":"Invoice view",
                                                "type":"object"
                                            },
                                            "type":"array"
                                        }
                                    },
                                    "required":[
                                        "invoices",
                                        "common"
                                    ],
                                    "title":"Invoices",
                                    "type":"object"
                                }
                            }
                        },
                        "description":"List of invoices sucessfully returned."
                    },
                    "default":{
                        "content":{
                            "application/json":{
                                "schema":{
                                    "additionalProperties":false,
                                    "properties":{
                                        "detail":{
                                            "example":"This thing and that thing are broken, please fix them",
                                            "type":"string"
                                        },
                                        "status":{
                                            "example":499,
                                            "type":"integer"
                                        },
                                        "title":{
                                            "example":"Broken things",
                                            "type":"string"
                                        },
                                        "type":{
                                            "example":"about:blank",
                                            "type":"string"
                                        }
                                    },
                                    "required":[
                                        "status",
                                        "title",
                                        "type",
                                        "detail"
                                    ],
                                    "title":"Error description",
                                    "type":"object"
                                }
                            }
                        },
                        "description":"Probably an error"
                    }
                },
                "summary":"Get a list of invoices of a booking.",
                "tags":[
                    "invoices"
                ]
            },
            "parameters":[
                {
                    "description":"ID of the booking.",
                    "in":"path",
                    "name":"booking_id",
                    "required":true,
                    "schema":{
                        "type":"integer"
                    }
                }
            ]
        },
    },
    "security":[
        {
            "PartnerTokenAuth":[

            ]
        },
        {
            "SimpleTokenAuth":[

            ]
        },
        {
            "TokenAuth":[

            ]
        },
        {
            "UserAppTokenAuth":[

            ]
        }
    ],
    "servers":[
        {
            "url":"/mmb/v1/bff"
        }
    ],
    "tags":[
        {
            "description":"Views related to shopping basket.",
            "name":"basket"
        },
        {
            "description":"Views related to check-in.",
            "name":"check-in"
        },
        {
            "description":"Common views.",
            "name":"common"
        },
        {
            "description":"Views related to invoices.",
            "name":"invoices"
        },
        {
            "description":"Views related to refund requests.",
            "name":"refunds-requests"
        },
        {
            "description":"Views related to refund alternative methods.",
            "name":"refunds-alternative-method"
        },
        {
            "description":"Views related to credit incentivisation refunds.",
            "name":"refunds-credits-incentivisation"
        },
        {
            "description":"Views related to out of pocket refunds.",
            "name":"refunds-out-of-pocket"
        }
    ]
}

export default mockOpenApi
